export const POST_VENUE_ACCOMMODATION = 'VENUE_ACCOMMODATION';
export const EDIT_ACCOMMODATION = 'EDIT_LISTING';
export const DELETE_ACCOMMODATION = 'DELETE_LISTING';
export const BOOKING_VENUE = 'BOOKING';
